// src/herd/fleet.ts — @herdctl/core FleetManager bootstrap for Warren.
//
// Boots a FleetManager from a generated ZERO-AGENT herdctl.yaml (fleet + defaults
// only), then lets the pipeline register review agents dynamically at run time via
// addAgent({ replace: true }). This module owns the fleet lifecycle and exposes a
// small wrapper so the rest of Warren never touches FleetManager internals.
//
// It does NOT own run orchestration (that lives in src/herd/run.ts): `trigger`
// here is a thin, typed pass-through to fleet.trigger.
//
// Lifecycle (proven in scripts/spike.ts): new FleetManager({configPath,stateDir})
// → initialize() → start(). start() is needed even with zero schedules.

import { promises as fs } from "node:fs";
import * as path from "node:path";
import { stringify as yamlStringify } from "yaml";
import {
  FleetManager,
  type AgentInfo,
  type InjectedMcpServerDef,
  type SDKMessage,
  type TriggerResult,
} from "@herdctl/core";
import type { ReviewerAgentConfig } from "./reviewer.js";
import { REVIEWER_DENIED_TOOLS, STATIC_REVIEWER_TOOLS } from "./reviewer.js";

/** Fleet-level defaults written into the generated herdctl.yaml `defaults` block.
 *  Every field is optional; sensible Warren defaults fill the gaps. These deep-merge
 *  into every runtime-added agent, but each agent still sets runtime/model/tools
 *  explicitly (defaults.runtime in particular is dropped by core's loader). */
export interface FleetDefaults {
  runtime?: string;
  model?: string;
  maxTurns?: number;
  permissionMode?: string;
  allowedTools?: string[];
  deniedTools?: string[];
}

export interface CreateFleetOptions {
  /** Base data dir. The generated herdctl.yaml lives here; state under `${dataDir}/.herdctl`. */
  dataDir: string;
  /** Overrides for the generated config's `defaults` block. */
  defaults?: FleetDefaults;
}

/** Options accepted by the wrapper's `trigger` — a subset of core's TriggerOptions
 *  passed straight through. */
export interface FleetTriggerOptions {
  prompt?: string;
  /** string = resume that session; null = force NEW; undefined = agent fallback. */
  resume?: string | null;
  /** Injected in-process MCP servers. Record KEY is the tool namespace (`mcp__<key>__*`). */
  injectedMcpServers?: Record<string, InjectedMcpServerDef>;
  /** Per-SDK-message streaming callback. */
  onMessage?: (m: SDKMessage) => void | Promise<void>;
  /** Fires with the job id mid-flight → enables cancel/supersede. */
  onJobCreated?: (jobId: string) => void | Promise<void>;
  /** Trigger origin; defaults to "manual". */
  triggerType?: string;
  /** Per-trigger system-prompt suffix (Warren's review rules + hardening). */
  systemPromptAppend?: string;
}

/** Small wrapper around a live FleetManager. Everything downstream uses this. */
export interface FleetWrapper {
  /** The underlying FleetManager (escape hatch for session accessors etc.). */
  fleet: FleetManager;
  /** Register (or replace) a review agent. Idempotent by agent name. */
  addReviewAgent(cfg: ReviewerAgentConfig): Promise<AgentInfo>;
  /** Fire an ad-hoc turn on `agentName`; resolves when the turn completes. */
  trigger(agentName: string, opts: FleetTriggerOptions): Promise<TriggerResult>;
  /** Cancel an in-flight job (supersede). Benign no-op if already finished. */
  cancel(jobId: string): Promise<void>;
  /** Stop the fleet. Idempotent — safe to call more than once. */
  stop(): Promise<void>;
}

const GENERATED_HEADER =
  "# GENERATED by src/herd/fleet.ts — do not hand-edit.\n" +
  "# Warren boots from this zero-agent config, then registers review agents at runtime.\n";

/** Build the zero-agent config object written to disk. */
function buildZeroAgentConfig(defaults?: FleetDefaults): Record<string, unknown> {
  return {
    version: 1,
    fleet: {
      name: "warren",
      description: "Warren PR-review fleet (agents registered at runtime).",
    },
    defaults: {
      runtime: defaults?.runtime ?? "cli",
      model: defaults?.model ?? "claude-opus-4-8",
      max_turns: defaults?.maxTurns ?? 200,
      permission_mode: defaults?.permissionMode ?? "acceptEdits",
      // SECURITY: default to the STATIC (no-Bash) tool set. Each review agent sets its
      // own allowed_tools explicitly (which wins), so this default only governs any agent
      // that doesn't — and it should fail safe, not hand out Bash on untrusted code.
      allowed_tools: defaults?.allowedTools ?? STATIC_REVIEWER_TOOLS,
      denied_tools: defaults?.deniedTools ?? REVIEWER_DENIED_TOOLS,
    },
  };
}

/** Write the zero-agent herdctl.yaml if it does not already exist. Returns the path. */
async function ensureConfigFile(configPath: string, defaults?: FleetDefaults): Promise<void> {
  try {
    await fs.access(configPath);
    return; // already present — leave it alone
  } catch {
    // fall through to write
  }
  const yaml = GENERATED_HEADER + yamlStringify(buildZeroAgentConfig(defaults));
  await fs.mkdir(path.dirname(configPath), { recursive: true });
  await fs.writeFile(configPath, yaml, "utf8");
}

/**
 * Boot a FleetManager for Warren: generate the zero-agent config (if absent),
 * construct → initialize → start, and return a small lifecycle wrapper.
 */
export async function createFleet(opts: CreateFleetOptions): Promise<FleetWrapper> {
  const dataDir = path.resolve(opts.dataDir);
  const stateDir = path.join(dataDir, ".herdctl");
  const configPath = path.join(dataDir, "herdctl.yaml");

  await fs.mkdir(dataDir, { recursive: true });
  await ensureConfigFile(configPath, opts.defaults);

  const fleet = new FleetManager({ configPath, stateDir });
  await fleet.initialize();
  await fleet.start();

  let stopped = false;

  return {
    fleet,

    async addReviewAgent(cfg: ReviewerAgentConfig): Promise<AgentInfo> {
      return fleet.addAgent(cfg, { replace: true });
    },

    async trigger(agentName: string, options: FleetTriggerOptions): Promise<TriggerResult> {
      return fleet.trigger(agentName, undefined, {
        prompt: options.prompt,
        resume: options.resume,
        injectedMcpServers: options.injectedMcpServers,
        onMessage: options.onMessage,
        onJobCreated: options.onJobCreated,
        triggerType: options.triggerType ?? "manual",
        systemPromptAppend: options.systemPromptAppend,
      });
    },

    async cancel(jobId: string): Promise<void> {
      // JobNotFoundError (turn already finished) is a benign no-op.
      await fleet.cancelJob(jobId).catch(() => {});
    },

    async stop(): Promise<void> {
      if (stopped) return;
      stopped = true;
      await fleet.stop({ waitForJobs: false }).catch(() => {});
    },
  };
}
