/**
 * Warren core-integration spike.
 *
 * Proves that a @herdctl/core FleetManager, running an agent on the CLI runtime
 * (Max plan `claude` binary), can be given an injected in-process MCP server and
 * will actually CALL a tool on it, with THIS host process capturing the call.
 *
 * Run: cd .../warren && env -u NODE_ENV npx tsx scripts/spike.ts
 */
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { FleetManager, type InjectedMcpServerDef } from "@herdctl/core";

// ---------------------------------------------------------------------------
// 0. Host-side capture array — the whole point of the spike.
// ---------------------------------------------------------------------------
const captured: Array<Record<string, unknown>> = [];

// ---------------------------------------------------------------------------
// 1. Temp workspace: stateDir + a generated zero-agent herdctl.yaml.
// ---------------------------------------------------------------------------
const workDir = mkdtempSync(join(tmpdir(), "warren-spike-"));
const stateDir = join(workDir, "data");
const configPath = join(workDir, "herdctl.yaml");

const configYaml = `# GENERATED by scripts/spike.ts — do not hand-edit.
version: 1
fleet:
  name: warren-spike
  description: Warren core-integration spike (agents registered at runtime).
defaults:
  max_turns: 8
  permission_mode: acceptEdits
  allowed_tools: ["Read", "Bash", "Glob", "Grep"]
`;
writeFileSync(configPath, configYaml, "utf8");

// ---------------------------------------------------------------------------
// 3. Injected MCP server def: ONE tool `record_finding`.
//    NOTE: herdctl's InjectedMcpToolDef takes a JSON-Schema `inputSchema`
//    (herdctl builds the zod shape internally for the SDK path); it does NOT
//    take a zod object directly. So the "zod input" from the brief is expressed
//    as the equivalent JSON Schema below.
// ---------------------------------------------------------------------------
const spikeDef: InjectedMcpServerDef = {
  name: "spike-server", // cosmetic on the CLI path; the record KEY is what matters
  version: "0.1.0",
  tools: [
    {
      name: "record_finding",
      description:
        "Record a single code-review finding. Call exactly once for this test.",
      inputSchema: {
        type: "object",
        properties: {
          path: { type: "string", description: "File path of the finding." },
          line: { type: "number", description: "Line number." },
          severity: { type: "string", description: "Severity, e.g. high." },
          title: { type: "string", description: "Short finding title." },
        },
        required: ["path", "line", "severity", "title"],
      },
      handler: async (args) => {
        captured.push(args);
        return {
          content: [
            { type: "text", text: `Recorded finding: ${String(args.title)}` },
          ],
        };
      },
    },
  ],
};

// ---------------------------------------------------------------------------
// Model id: try the full id first, fall back to the alias.
// ---------------------------------------------------------------------------
const MODEL_CANDIDATES = ["claude-opus-4-8", "opus"] as const;

async function main() {
  const fleet = new FleetManager({ configPath, stateDir });
  await fleet.initialize();
  await fleet.start();

  let workingModel: string | null = null;
  let lastError: unknown = null;

  try {
    for (const model of MODEL_CANDIDATES) {
      captured.length = 0;
      console.log(`\n=== Attempt with model="${model}" ===`);

      await fleet.addAgent(
        {
          name: "reviewer",
          description: "Spike reviewer agent.",
          working_directory: workDir,
          runtime: "cli",
          model,
          permission_mode: "acceptEdits",
          max_turns: 8,
          // Must include mcp__spike__* so the injected tool is allow-listed.
          allowed_tools: ["Read", "Bash", "mcp__spike__*"],
          instances: { max_concurrent: 1 },
        },
        { replace: true },
      );

      const prompt =
        "You are testing a tool. Call the `record_finding` tool exactly once " +
        "with path='src/foo.ts', line=42, severity='high', title='test finding'. " +
        "Then reply DONE and stop.";

      try {
        const result = await fleet.trigger("reviewer", undefined, {
          prompt,
          resume: null,
          triggerType: "manual",
          injectedMcpServers: { spike: spikeDef }, // record key "spike" => mcp__spike__record_finding
          onMessage: (m: any) => {
            const t = m?.type;
            if (t === "assistant") {
              const blocks = m?.message?.content;
              if (Array.isArray(blocks)) {
                for (const b of blocks) {
                  if (b?.type === "text" && b.text?.trim()) {
                    console.log(`  [assistant] ${b.text.trim().slice(0, 200)}`);
                  } else if (b?.type === "tool_use") {
                    console.log(
                      `  [tool_use] ${b.name} ${JSON.stringify(b.input)}`,
                    );
                  }
                }
              } else if (typeof m?.content === "string" && m.content.trim()) {
                console.log(`  [assistant] ${m.content.trim().slice(0, 200)}`);
              }
            } else if (t === "result") {
              console.log(
                `  [result] success=${m?.success ?? m?.subtype} session=${m?.session_id}`,
              );
            } else if (t === "system") {
              console.log(`  [system] ${m?.subtype ?? ""}`);
            }
          },
        });

        console.log(
          `  trigger returned: success=${result.success} error=${result.error?.message ?? "none"}`,
        );

        if (result.success) {
          workingModel = model;
          break;
        }
        lastError = result.error;
        // If the model id was rejected, fall through to the next candidate.
        console.log(`  model="${model}" did not succeed; trying next candidate.`);
      } catch (err) {
        lastError = err;
        console.log(
          `  trigger threw for model="${model}": ${(err as Error)?.message}`,
        );
      }
    }
  } finally {
    await fleet.stop({ waitForJobs: false }).catch(() => {});
  }

  // -------------------------------------------------------------------------
  // 5. Assertions.
  // -------------------------------------------------------------------------
  console.log(`\n=== RESULT ===`);
  console.log(`working model id: ${workingModel ?? "NONE"}`);
  console.log(`captured.length = ${captured.length}`);
  console.log(`captured = ${JSON.stringify(captured, null, 2)}`);

  const expected = {
    path: "src/foo.ts",
    line: 42,
    severity: "high",
    title: "test finding",
  };

  const fail = (why: string) => {
    console.error(`\nSPIKE FAIL: ${why}`);
    if (lastError) console.error(`last error: ${(lastError as Error)?.message ?? lastError}`);
    process.exit(1);
  };

  if (!workingModel) fail("no model id produced a successful turn");
  if (captured.length !== 1)
    fail(`expected captured.length === 1, got ${captured.length}`);

  const got = captured[0];
  for (const [k, v] of Object.entries(expected)) {
    // line may come back as number or numeric string depending on the bridge.
    const a = k === "line" ? Number(got[k]) : got[k];
    const b = k === "line" ? Number(v) : v;
    if (a !== b) fail(`captured.${k} = ${JSON.stringify(got[k])}, expected ${JSON.stringify(v)}`);
  }

  console.log(`\nSPIKE PASS`);
  console.log(JSON.stringify(captured[0], null, 2));
  console.log(`(model id that worked: ${workingModel})`);
  process.exit(0);
}

main().catch((err) => {
  console.error(`\nSPIKE FAIL: unhandled error`);
  console.error(err);
  process.exit(1);
});
